In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [3]:
# XOR dataset

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    0,
    1,
    1,
    0
])

print("Input Data:")
print(X)

print("Output:")
print(y)

Input Data:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Output:
[0 1 1 0]


In [4]:
# Create Neural Network Model

model = MLPClassifier(
    hidden_layer_sizes=(2,),
    activation='logistic',
    solver='lbfgs',
    max_iter=1000
)

# Train the model
model.fit(X,y)

print("Training completed")

Training completed


In [5]:
# Prediction

prediction = model.predict(X)

print("Predicted Output:")
print(prediction)

# Accuracy
accuracy = accuracy_score(y,prediction)

print("Accuracy:")
print(accuracy*100,"%")

Predicted Output:
[0 1 1 0]
Accuracy:
100.0 %


In [6]:
test = np.array([[1,0]])

result = model.predict(test)

print("Test Input:")
print(test)

if result[0] == 1:
    print("Output: 1")
else:
    print("Output: 0")

Test Input:
[[1 0]]
Output: 1
